# Generated by Django 4.2.4 on 2023-08-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_createlisting_price_alter_userbid_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userbid',
            name='bid',
            field=models.FloatField(),
        ),
    ]
