# Generated by Django 4.2.4 on 2023-08-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_createlisting_price_alter_userbid_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbid',
            name='bid_time',
        ),
    ]
