# Generated by Django 4.2.4 on 2023-08-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_usercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='body',
            new_name='content',
        ),
    ]
